version: '3'

services:
  emulated_hue:
    build:
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
      target: dev_pycharm
    restart: "no"
    environment:
      - DATA_DIR=/config
      - HASS_URL=http://192.168.1.1:8123
      - HASS_TOKEN=yourtokenhere
      - VERBOSE=True
    volumes:
      - ../config:/config
#    network_mode: "host"
    ports:
      - '80:80'
      - '443:443'
      - '2100:2100/udp'

# Host networking is required for discovery development
# If discovery is needed in development, use a Linux machine or venv
# Host networking for Docker does not work on Windows or MacOS


